import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Nettdisplay from '@/components/Nettdisplay'
import Navbar_sub from '@/components/Navbar_sub'



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar_sub />
      <Nettdisplay />
    </>
  )
}
